### ISSUE TITLE
could not start cosbench in centos 6.3

### ISSUE THREAD

**Issue by aravindhramu** [intel-cloud/cosbench#100]
Not sure what the issue is. Have installed all the required dependencies mentioned in the doc.

[root@ip-10-164-102-121 0.3.1.2]# sh cosbench-start.sh 
Launching osgi framwork ... 
Successfully launched osgi framework!
Booting cosbench  ... 
Successfully started cosbench !
An error has occurred.  See the log file
/root/0.3.1.2/conf/./1377082141750.log
[root@ip-10-164-102-121 0.3.1.2]# cat /root/0.3.1.2/conf/./1377082141750.log
!SESSION Wed Aug 21 10:49:01 UTC 2013 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2013-08-21 10:49:01.782
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.RuntimeException: Could not find framework
    at org.eclipse.equinox.launcher.Main.getBootPath(Main.java:978)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:557)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1386)

**Comment by suab321321** [comment]
@aravindhramu I m facing this same issue could you please tell how to solved it by setting path
