### ISSUE TITLE
Add option to allow for unique object names across drivers

### ISSUE THREAD

**Issue by agama** [intel-cloud/cosbench#129]
In some situations, ensuring that the object names generated by drivers are guaranteed to be unique is a requirement.  It would be nice to have an option supplied via the XML that would enable this feature, or to have a substitution string as a part of the object name prefix that would be recognised and replaced with the driver ID (e.g. obj_%d, where %d would be replaced).

**Comment by AlvinOscar** [comment]
Hi @ywang19,    

In our tests, the "division" property prevents container-object names from being reused, but only in smaller workloads with < 4 drivers.   In our tests using 17 drivers, the following causes workload configuration causes the creation of between 5 and 11 objects with a container-object name that was already created during the workload.

```
<work name="main" division="container" workers="17" totalOps="800">
...... containers=r(1,35);objects=u(1,900)... />
```

Are we mis-using the "division" field?   
Could you provide a sample workload that will not have overwrites, but will have 17 workers and 800 writes?

Btw, we are a fan of your work!

Thank you,
Eric
