### ISSUE TITLE
multiple drivers on the same physical node

### ISSUE THREAD

**Issue by ywang19** [intel-cloud/cosbench#210]
User sometimes requires to run multiple drivers on the same physical node, although it's supported, current scripts don't well fit this case, need improve.

**Comment by liyuanwa** [comment]
Starting Drivers
•	Edit conf/model_driver.conf on driver nodes, if desired
•	Edit conf/model_driver-tomcat-server.xml, if want change tomcat information
•	Launch drivers with script start-driver.sh
start-driver.sh <n> <ip> <base-port>
First parameter means the number of drivers , second is drivers’ip, last one is base-port for listen. You can choose any of them if want.
sh start-driver.sh
By default, COSBench start one driver on 127.0.0.1 and listens on port 18088
sh start-driver.sh 3
with one parameter <n>, start three drivers on 127.0.0.1 and listen on ports 18088,18188,18288
sh start-driver.sh 192.168.0.11
with one parameter <ip>, start one driver  on 192.168.0.11 and listens on port 18088
sh start-driver.sh 16088
with one parameter <base-port>, start one driver on 127.0.0.1 and listens on port 16088
sh start-driver.sh  2  192.168.0.11 16088
with three parameters <n> <ip> <base-port>, start three drivers on 192.168.0.11 and listen on port 16088,16188

•	Ensure that all drivers are accessible from the controller using an HTTP connection. 
        By connecting with Curl, one valid HTML file is expected in the console: 
curl http://<ip >:<port>/driver/index.html
