### ISSUE TITLE
Keystone needs to accept region name as parameter.

### ISSUE THREAD

**Issue by imkarrer** [intel-cloud/cosbench#236]
A user can only benchmark the proxies on the default first region.  I would like the ability to target any region's proxies with keystone auth.

**Comment by xiaoerlyl** [comment]
You can't specify a region name when you access the storage service  with keystone auth. The region name of a storage service is initialized when you setup the storage service and its endpoint with keystone

**Comment by imkarrer** [comment]
When there are multiple Regions in a Swift deployment, it is standard for there to be an endpoint for each Region for keystone.  OS_REGION_NAME is the parameter which keystone evaluates to determine which Region's endpoint to use.

Below is a direct quote from the python-keystoneclient readme
https://github.com/openstack/python-keystoneclient

Since the Identity service can return multiple regions in the service catalog, you can specify the one you want with --os-region-name (or export OS_REGION_NAME):

export OS_REGION_NAME=north
Warning

If a region is not specified and multiple regions are returned by the Identity service, the client may not access the same region consistently.

**Comment by xiaoerlyl** [comment]
In COSBench, we just used keystone REST API. It seems that there is no Region parameter in keystone REST API.
This is the quote from openstack identity api:  http://developer.openstack.org/api-ref-identity-v2.html

**Comment by xiaoerlyl** [comment]
We have added a region parameter for keystone auth to specify the target region. Thanks for your advice.

**Comment by xiaoerlyl** [comment]
23a22ce6293a5942c31263f290be081b232c8654
