### ISSUE TITLE
Mixed Workloads (Read,Write,Delete) cause low read success rate.

### ISSUE THREAD

**Issue by nakleppa** [intel-cloud/cosbench#254]
Running a workload with a mix of reads, writes, and delete operations in the same workstage causes Cosbench to have an extremely low success ratio for read operations.  Logs indicate that this is due to 404 not found errors.  Given that the only success ratio affected is the reads, it is suspected that the deleted objects are not being removed from the list of objects available for access.

**Comment by ywang19** [comment]
if you set read/write/delete working on the container range, object range, yes, you will see low success ratio for read, as many objects may be deleted when read. 
to mix those operations in one work, a normal approach is to set operators working on isolated container/object range to avoid confliction. e.g,
   read: container [1,10], write: container [11,20], delete: container [21,30].
