### ISSUE TITLE
Attempting to view workload main stage details leads to 400 Bad Request

### ISSUE THREAD

**Issue by nakleppa** [intel-cloud/cosbench#255]
The stage details can be viewed for the init, prepare, cleanup, and dispose stages, but attempting to do the same for the main stage causes an error.  The main stage in question has two operations, read and write.

![cosbench_issue1](https://cloud.githubusercontent.com/assets/11396174/6582197/edd6c05a-c718-11e4-8c67-eea4c9dadc80.jpg)
![cosbench_issue2](https://cloud.githubusercontent.com/assets/11396174/6582198/edda1fca-c718-11e4-89f9-7e12343db558.jpg)

**Comment by ywang19** [comment]
Could you paste the workload.log and workload-config.xml for w13 (under “archive” folder)?

**Comment by nakleppa** [comment]
I have attached the logs as a zip file, however to get github to allow the attachment, the file extension has been changed.  In order to open the zip file, you will first have to rename the file such that it has a .zip extension instead of jpg.

![logs](https://cloud.githubusercontent.com/assets/11396174/6647653/f894376c-c98d-11e4-92ad-ee4621b32bc4.jpg)

**Comment by nakleppa** [comment]
Also, the same problem occurs on this and other workloads of mixed operation types when clicking "view details" under the performance matrix.  The two issues may be related.

**Comment by ywang19** [comment]
The issue can't be reproduced in 0.4.2.c3 release, I will temporarily close it, and revisit if get new triggers.
