### ISSUE TITLE
Cosbench hangs while running tests.

### ISSUE THREAD

**Issue by ovjh** [intel-cloud/cosbench#262]
When I am running 100 cosbench tests against s3 server. After few (~7/8) tests are over cosbench hangs and thereafter it stops creating objects. I don't see any PUT/GET requests to s3 server from cosbench. However I see following log entries getting printed in "0.4.1.0/log/mission/MB7AD081378.log (latest log file)"

2015-04-02 10:23:10,635 [INFO] [NoneStorage] - performing PUT at /s3napatest-512-512-1024-50-50-64kb-4318/myobjects9

I used same s3 server with aws cli and I am able to create objects with it inside same bucket. Also if I execute "sar -n DEV 3" on the node running cosbench then I don't see any network traffic. So the cosbench is not pushing anything but can't understand why?

any idea what might be going on?

**Comment by ovjh** [comment]
Let me know if anything is required...I would be happy to share the tests if needed...

**Comment by ovjh** [comment]
It doesn't allow to upload xml file.. so uploading it as ([DOT]jpg)
![test1 xml](https://cloud.githubusercontent.com/assets/6015220/6975651/a41a3738-d953-11e4-96e0-a6040971da57.jpg)

**Comment by ywang19** [comment]
recently, I did a check on current code, and fixed some race conditioning issue at workload execution. so build a 0.4.2 beta version soon. feel free to try that version to verify if your issue is resolved.

**Comment by ywang19** [comment]
hello, the v0.4.2 RC1 is just published at https://github.com/intel-cloud/cosbench/releases/download/v0.4.2.c1/0.4.2.c1.zip, could you have a try with this version?

**Comment by ovjh** [comment]
actually the problem was that .. S3Storage.java doesn't recreate the AmazonS3 client connection if it is broken... Ideally if you get say AmazonClientException which is not AmazonServiceException then we should recreate the connection... what do you think??

**Comment by ywang19** [comment]
the enhancement to reinitialize client will be included in 0.4.2.c3, feel free to help verify it.
