### ISSUE TITLE
v0.4.2.c1: Swift/Keystone regression

### ISSUE THREAD

**Issue by zoran-rajic** [intel-cloud/cosbench#267]
It seems there is a regression with the Swift storage using Keystone authentication, introduced on v0.4.2.c1 branch: the code is ignoring the Keystone authentication, and defaults to internal authentication values.  This used to work correctly on v0.4.1.

The following change seems to be the root-cause:
- from 216d31bd:
--- a/dev/cosbench-driver/src/com/intel/cosbench/driver/agent/AuthAgent.java
+++ b/dev/cosbench-driver/src/com/intel/cosbench/driver/agent/AuthAgent.java
@@ -74,6 +74,8 @@ class AuthAgent extends AbstractAgent {
     private AuthContext login() {
         Logger logger = getMissionLogger();
         AuthAPI authApi = workerContext.getAuthApi();
+        if(authApi instanceof NoneAuth) // bypass caching handling for NoneAuth.
+               return null;
         int attempts = 0;
         while (attempts++ < loginAttempts - 1)
             try {

Since the KeystoneAuth is actually a subclass of NoneAuth, the 'null' is returned;  this causes SwiftStorage.setAuthContext() to use the default settings (authToken=AUTH_xxx, storageUrl=http://127.0.0.1:8080/auth/v1.0), and the KeystoneAuth object is never used.

**Comment by ywang19** [comment]
Yes, it’s an issue, I will update the binary package soon.


Thanks,
-yaguang

**Comment by ywang19** [comment]
fixed, please download 0.4.2.c2 to verify.
