### ISSUE TITLE
S3: Timeout modifies only the connection timeout

### ISSUE THREAD

**Issue by zoran-rajic** [intel-cloud/cosbench#270]
Specifying the timeout value in the S3 workload, ie:
```xml
  <storage type="s3" config="timeout=600000;accesskey=AKIA..."/>
```
.. modifies only the socket connection timeout.

_Expectation_:
* the given timeout should modify both socket-connection, and socket-inactivity timeouts.

**Comment by ywang19** [comment]
Yes, it’s an expected enhancement. So far only one timeout value, from my perspective, more tcp settings could be added as options beside those two timeouts.

-yaguang

**Comment by zoran-rajic** [comment]
Hello Yaguang,

It's good to know you were preparing the same enhancement.  Apropos, the fix is trivial (see https://github.com/zoran-rajic/cosbench/commit/8f1de4c2b8c0f5aa4cf695a086d5bb66fec32659).

Thanks,
            Zoran

**Comment by ywang19** [comment]
Hi Zoran,

Could you pull your fix to upstream?


-yaguang

**Comment by zoran-rajic** [comment]
Hi Yaguang,

Created pull request @ https://github.com/intel-cloud/cosbench/pull/271

Thanks,
           Zoran
