### ISSUE TITLE
FreeMarker template error: The following has evaluated to null or missing ...

### ISSUE THREAD

**Issue by ywang19** [intel-cloud/cosbench#274]
If you reboot Cosbench, the list of completed workloads goes away. It is possible to load archived workloads, but if you do, and try to look at their results, you get error.

Furthermore, if you load the archived workloads, and then run a new workload, it appears at the end of the archived list, and when you try to look at its results, you also get the display with the thrown exceptions.

It means that if you ever have to reboot Cosbench, you are going to have to read the results out of the CSV files in the archived directory structure – doable, but bloody inconvenient.

**Comment by BodihTao** [comment]
Hi I have met this issue again in 0.4.2.c4 version. so how can i fix it ?  rm the cvs is work ?
