### ISSUE TITLE
no response with any data when running on RHEL 7.1

### ISSUE THREAD

**Issue by ywang19** [intel-cloud/cosbench#276]
We have just started using COSBENCH on a new RHEL7.1 platform and encountered new problems.
I know it is not your primary platform but I wonder if you could point how to debug it.

The symptoms are quite strange:
The cosbench drivers and a controller seems to be started (according to the start-all.sh output),
The netstat –an shows that the cosbench is listening on the port 19088.

However when trying to access the controller from a browser or even from wget (wget <url>) – the server simply does not seem to respond with any data.

I am attaching the logs directory which has a libs.log with plenty to java exceptions.
Could you please take a look and tell us what you think?

**Comment by gonewest818** [comment]
For what it's worth, we are running cosbench on RHEL 7.1 without any of those symptoms.

**Comment by mratner** [comment]
The issue is already closed, but just wanted to add another point of reference - we're also running RHEL 7.1 and haven't seen any of these symptoms.
