### ISSUE TITLE
Cosbench dosen't works with selfi signed certificate

### ISSUE THREAD

**Issue by alebeta90** [intel-cloud/cosbench#277]
Hello friends!

OS:Ubuntu Server
im using cosbench 0.4.2 and i want test my S3 environment with SSL, but is not working i recieve the next output:

2015-06-19 12:35:42,481 [ERROR] [AbstractOperator] - worker 1 fail to perform operation ga-cosbench1
com.intel.cosbench.api.storage.StorageException: com.amazonaws.AmazonClientException: Unable to execute HTTP request: peer not authenticated

i read that in other version cosbench support self signed certificate. But here is not working

Thanks! and all the best.
Alejandro B

**Comment by ywang19** [comment]
Hi Alejandro,

Normally, if you use a “https” protocol in “endpoint” parameter, the connection will automatically switch to use SSL. Could you paste the workload xml file?


-yaguang

**Comment by alebeta90** [comment]
Hello Yaguang!

Yes i already read about cosbench automatically must switch to use ssl, but i have this problem. Let me show you the workload.

Thanks for your Help!! and all the best.

<?xml version="1.0" encoding="UTF-8" ?>
<workload name="s3-sample" description="sample benchmark for s3">

  <storage type="s3" config="accesskey=user@example.com;secretkey=secretkey;endpoint=https://ecs.example.com:443" />

  <workflow>

    <workstage name="init">
      <work type="init" workers="1" config="cprefix=ga-cosbench;containers=r(1,30)" />
    </workstage>

    <workstage name="prepare">
      <work type="prepare" workers="1" config="cprefix=ga-cosbench;containers=r(1,30);objects=r(1,30);sizes=c(64)KB" />
    </workstage>

    <workstage name="main">
      <work name="main" workers="8" runtime="30">
        <operation type="read" ratio="80" config="cprefix=ga-cosbench;containers=u(1,30);objects=u(1,30)" />
        <operation type="write" ratio="20" config="cprefix=ga-cosbench;containers=u(1,30);objects=u(11,30);sizes=c(1)GB" />

      </work>
    </workstage>

    <workstage name="cleanup">
      <work type="cleanup" workers="1" config="cprefix=ga-cosbench;containers=r(1,30);objects=r(1,30)" />
    </workstage>

    <workstage name="dispose">
      <work type="dispose" workers="1" config="cprefix=ga-cosbench;containers=r(1,30)" />
    </workstage>

  </workflow>

</workload>

**Comment by ywang19** [comment]
Could you paste the complete one? Especially important part is the <auth> and <storage> section.

**Comment by alebeta90** [comment]
<?xml version="1.0" encoding="UTF-8" ?>
<workload name="s3-sample" description="sample benchmark for s3">

  <storage type="s3" config="accesskey=user@example.com;secretkey=secretkey;endpoint=https://ecs.example.com:443" />

  <workflow>

    <workstage name="init">
      <work type="init" workers="1" config="cprefix=ga-cosbench;containers=r(1,30)" />
    </workstage>

    <workstage name="prepare">
      <work type="prepare" workers="1" config="cprefix=ga-cosbench;containers=r(1,30);objects=r(1,30);sizes=c(64)KB" />
    </workstage>

    <workstage name="main">
      <work name="main" workers="8" runtime="30">
        <operation type="read" ratio="80" config="cprefix=ga-cosbench;containers=u(1,30);objects=u(1,30)" />
        <operation type="write" ratio="20" config="cprefix=ga-cosbench;containers=u(1,30);objects=u(11,30);sizes=c(1)GB" />

      </work>
    </workstage>

    <workstage name="cleanup">
      <work type="cleanup" workers="1" config="cprefix=ga-cosbench;containers=r(1,30);objects=r(1,30)" />
    </workstage>

    <workstage name="dispose">
      <work type="dispose" workers="1" config="cprefix=ga-cosbench;containers=r(1,30)" />
    </workstage>

  </workflow>

</workload>

**Comment by alebeta90** [comment]
Hello Yaguang! I put the workload in pastebin, because for some reason here i cant paste all the workload, github like erease the section with the auth and storage label.

http://pastebin.com/Ay3d5g4x

thanks a lot! have  a nice day

**Comment by ywang19** [comment]
I can’t access the pastebin ☹.

**Comment by alebeta90** [comment]
and this one https://paste.fedoraproject.org/236085/43514147/ ??

**Comment by ywang19** [comment]
could u have a try on 0.4.2.c2? the 0.4.2.c1 has a bug which will break other than ceph.

**Comment by Ravi-Tripathi21** [comment]
I am facing the same issue with cosbench 0.4.1.0. Trying to configure it for S3 with https access. but its failing with below error-

2015-10-05 03:10:12,343 [ERROR] [S3Storage] - connection is created:id:78
2015-10-05 03:10:12,366 [INFO] [NoneStorage] - performing PUT at /mycontainers1
2015-10-05 03:10:16,704 [ERROR] [S3Storage] - ERROR:Unable to execute HTTP request: Connection to https://MYHOSTNAME refused.


------------------------------
<auth type="none" config=""/>
    <storage type="s3" config="accesskey=MYKEY;secretkey=MYSECRETKEY;endpoint=https://MYHOSTNAME;path_style_access=true"/>

-------------------------

**Comment by ywang19** [comment]
For the "peer not athenticated" error, one is to use http:// instead of https:// to choose http protocol if https is not your exepcted. or, if you really expect https, this link may help, the basic idea is you'd make self-signed certificate into JVM trust store before issuing requests. 
http://stackoverflow.com/questions/12961570/sslpeerunverifiedexception-peer-not-authenticated

in short, the steps are:

1.Run the following command, replace $ADDRESS with the URL, minus the "https://":

echo -n | openssl s_client -connect $ADDRESS:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/$ADDRESS.cert


2.Run the following command, replace $ALIAS a short name for the key, $ADDRESS with the cert name from above, $PATH with the path to cacerts in your JRE.

sudo keytool -importcert -alias "$ALIAS" -file /tmp/$ADDRESS.cert -keystore $PATH/cacerts -storepass changeit
