### ISSUE TITLE
cosbench-0.5.0 and cosbench-master can not start

### ISSUE THREAD

**Issue by dwj192** [intel-cloud/cosbench#285]
use 0.4.2.c3  i can launch
···
Launching osgi framwork ... 
Successfully launched osgi framework!
Booting cosbench driver ... 
..
Starting    cosbench-log_0.4.2    [OK]
Starting    cosbench-tomcat_0.4.2    [OK]
Starting    cosbench-config_0.4.2    [OK]
Starting    cosbench-http_0.4.2    [OK]
Starting    cosbench-cdmi-util_0.4.2    [OK]
Starting    cosbench-core_0.4.2    [OK]
Starting    cosbench-core-web_0.4.2    [OK]
Starting    cosbench-api_0.4.2    [OK]
Starting    cosbench-mock_0.4.2    [OK]
Starting    cosbench-ampli_0.4.2    [OK]
Starting    cosbench-swift_0.4.2    [OK]
Starting    cosbench-keystone_0.4.2    [OK]
Starting    cosbench-httpauth_0.4.2    [OK]
Starting    cosbench-s3_0.4.2    [OK]
Starting    cosbench-librados_0.4.2    [OK]
Starting    cosbench-scality_0.4.2    [OK]
Starting    cosbench-cdmi-swift_0.4.2    [OK]
Starting    cosbench-cdmi-base_0.4.2    [OK]
Starting    cosbench-driver_0.4.2    [OK]
Starting    cosbench-driver-web_0.4.2    [OK]
Successfully started cosbench driver!
Listening on port 0.0.0.0/0.0.0.0:18089 ... 
Persistence bundle starting...
Persistence bundle started.
----------------------------------------------
!!! Service will listen on web port: 18088 !!!
----------------------------------------------

======================================================

Launching osgi framwork ... 
Successfully launched osgi framework!
Booting cosbench controller ... 
.
Starting    cosbench-log_0.4.2    [OK]
.
Starting    cosbench-tomcat_0.4.2    [OK]
Starting    cosbench-config_0.4.2    [OK]
Starting    cosbench-core_0.4.2    [OK]
Starting    cosbench-core-web_0.4.2    [OK]
Starting    cosbench-controller_0.4.2    [OK]
Starting    cosbench-controller-web_0.4.2    [OK]
Successfully started cosbench controller!
Listening on port 0.0.0.0/0.0.0.0:19089 ... 
Persistence bundle starting...
Persistence bundle started.
----------------------------------------------
!!! Service will listen on web port: 19088 !!!
----------------------------------------------
···

but use the host i start cosbench-0.5.0 and cosbench-master failed
```
ceph@node112:~/cos/release$ sudo sh start-all.sh 
cat: VERSION: No such file or directory
Launching osgi framwork ... 
Successfully launched osgi framework!
Booting cosbench driver ... 
...........................................................
Starting    cosbench-log_    [ERROR]
...........................................................
Starting    cosbench-tomcat_    [ERROR]
...........................................................
Starting    cosbench-config_    [ERROR]
...........................................................
Starting    cosbench-http_    [ERROR]
...........................................................
Starting    cosbench-cdmi-util_    [ERROR]
...........................................................
Starting    cosbench-core_    [ERROR]
...........................................................
Starting    cosbench-core-web_    [ERROR]
...........................................................
Starting    cosbench-api_    [ERROR]
.............
```

**Comment by dwj192** [comment]
the log
```
ceph@node112:~/cos/release$ sudo sh start-all.sh 
cat: VERSION: No such file or directory
Launching osgi framwork ... 
Successfully launched osgi framework!
Booting cosbench driver ... 
...........................................................
Starting    cosbench-log_    [ERROR]
...........................................................
Starting    cosbench-tomcat_    [ERROR]
...........................................................
Starting    cosbench-config_    [ERROR]
...........................................................
Starting    cosbench-http_    [ERROR]
...........................................................
Starting    cosbench-cdmi-util_    [ERROR]
...........................................................
Starting    cosbench-core_    [ERROR]
...........................................................
Starting    cosbench-core-web_    [ERROR]
...........................................................
Starting    cosbench-api_    [ERROR]
...........................................................
Starting    cosbench-mock_    [ERROR]
......^Cceph@node112:~/cos/release$ ls
cli.sh             cosbench-stop.sh  licenses  start-all.bat         start-controller.sh  stop-all.sh         web.bat
conf               javadoc           log       start-all.sh          start-driver.bat     stop-controller.sh  workloads
cosbench-start.sh  lib-src           scripts   start-controller.bat  start-driver.sh      stop-driver.sh      workspace
ceph@node112:~/cos/release$ cd log/
ceph@node112:~/cos/release/log$ ls
driver-boot.log
ceph@node112:~/cos/release/log$ cat driver-boot.log 
Error: Could not find or load main class org.eclipse.equinox.launcher.Main
ceph@node112:~/cos/release/log$
```

**Comment by dwj192** [comment]
it's my fault...

**Comment by ywang19** [comment]
Git cloning either the master or 0.5.0 branch can only give you the source repository, it’s required to have pre-built binaries to launch cosbench. Those pre-built binaries can be downloaded from https://github.com/intel-cloud/cosbench/releases .
