### ISSUE TITLE
how can i change the default auth and storage in the config web page ?

### ISSUE THREAD

**Issue by zphj1987** [intel-cloud/cosbench#291]
![](http://7xo9we.com1.z0.glb.clouddn.com/16-1-7/49187086.jpg)

the default choose not have the s3 ,how can i add it ?

**Comment by ywang19** [comment]
for S3, you just need choose authentication as "none", as s3 storage adapter embedded its authentication.

**Comment by zphj1987** [comment]
thank you  !  
 i will try it
