### ISSUE TITLE
Ncat conneciton refused

### ISSUE THREAD

**Issue by testabhi** [intel-cloud/cosbench#300]
./start-driver.sh
Launching osgi framwork ...
Successfully launched osgi framework!
Booting cosbench driver ...
Ncat: Connection refused.
.Ncat: Connection refused.
.Ncat: Connection refused.
.Ncat: Connection refused.
.Ncat: Connection refused.
.Ncat: Connection refused.
.Ncat: Connection refused.
.Ncat: Connection refused.
.Ncat: Connection refused.
.Ncat: Connection refused.

**Comment by jamshid** [comment]
I had similar error, check your /opt/cosbench/logs directory. I had forgotten to install java. Try:
`yum install -y nc java-1.7.0-openjdk`.
```
==> controller-boot.log <==
/usr/bin/nohup: failed to run command ‘java’: No such file or directory

==> driver-boot.log <==
/usr/bin/nohup: failed to run command ‘java’: No such file or directory
```
