### ISSUE TITLE
Assistance In Configuring  Worlkload

### ISSUE THREAD

**Issue by amitsidhim** [intel-cloud/cosbench#302]
Hello Team , 

I  am working with configuration   of workload  with amazon complaint s3 cloud. This basically connects with path based hostname. e.g http://s3.n8500:8167

I need to get this information on the workflow . Following is the sample file , not sure where things are going wrong. 

> <?xml version="1.0" encoding="UTF-8" ?>
> <workload name="s3-sample" description="sample benchmark for s3">
> 
>   <storage type="s3" config="accesskey=xxxxxxxx;secretkey=xxxxxx;endpoint=http://s3.ngsfdellpe:8143" />
> 
>   <workflow>
> 
>     <workstage name="init">
>       <work type="init" workers="1" config="containers=r(1,2)" />
>     </workstage>
> 
>     <workstage name="prepare">
>       <work type="prepare" workers="1" config="containers=r(1,2);objects=r(1,10);sizes=c(64)KB" />
>     </workstage>
> 
>     <workstage name="main">
>       <work name="main" workers="8" runtime="30">
>         <operation type="read" ratio="80" config="containers=u(1,2);objects=u(1,10)" />
>         <operation type="write" ratio="20" config="containers=u(1,2);objects=u(11,20);sizes=c(64)KB" />
>       </work>
>     </workstage>
> 
>     <workstage name="cleanup">
>       <work type="cleanup" workers="1" config="containers=r(1,2);objects=r(1,20)" />
>     </workstage>
> 
>     <workstage name="dispose">
>       <work type="dispose" workers="1" config="containers=r(1,2)" />
>     </workstage>
> 
>   </workflow>
> 
> </workload>

Kindly Help , 

Thanks in Advance

**Comment by amitsidhim** [comment]
This has been resolved. Actually, For the Emulated S3 storage it looks have to add a flag with  storage

config="path_style_access=true

**Comment by ywang19** [comment]
There is a sample workload configuration file in “conf” folder named s3-conf-sample.xml, you could use it as template. For your case, the <storage> section will look like:

<storage type="s3" config="accesskey=<accesskey>;secretkey=<scretkey>;path_style_access=true; proxyhost=<proxyhost>;proxyport=<proxyport>;endpoint=http://s3.n8500:8167" />



-yaguang
