### ISSUE TITLE
Creating large number of files. 

### ISSUE THREAD

**Issue by amitsidhim** [intel-cloud/cosbench#306]
Hello Team , 

I am trying to create around 1  million objects in  a container. These I need to set as Read 80%, Write 20% and Delete 5%. I am really not sure what to initially set the  number of objects to 1 million. 

In the section "Prepare Stage" I am trying to set the Object selector to 1000000. However I get following Error :: in the section "Config Workloads"

Note: ERROR: op ratio should sum to 100!

KIndly, assist , how to set the  object number to this size.

**Comment by gurvindersingh** [comment]
Change your ratio to 75%, 20% and 5% respectively. as in your current config the sum is more than 100% (105 to be precise)

**Comment by pranavPawar07** [comment]
@amitsidhim were you able to execute the workload successfully (for 1 million objects) ?
