### ISSUE TITLE
COSBench On RHEL 7.0

### ISSUE THREAD

**Issue by amitsidhim** [intel-cloud/cosbench#316]
Hello Team , 

Wanted to Check if COSBench can be installed on RHEL 7.0  or it can only be installed on Ubuntu. 

Thanks.

**Comment by ywang19** [comment]
It can be installed on CentOS 7, should be OK on RHEL 7.0.

**Comment by ywang19** [comment]
It can also run on SuSE 12 SP1 with the packages provided from here: https://susestudio.com/a/S1QYue/cosbench.

**Comment by amitsidhim** [comment]
Thanks for the Reply
