### ISSUE TITLE
When I write 10Gfile with cosbench fails, chunked is not working

### ISSUE THREAD

**Issue by Saber-Yang** [intel-cloud/cosbench#347]
the log
2017-03-15 16:44:45,750 [WARN] [S3Storage] - below exception encountered when creating object myobjects1 at mycontainers1: Failed to reset the request input stream;  If the request involves an input stream, the maximum stream buffer size can be configured via request.getRequestClientOptions().setReadLimit(int)

the xml
`    <workstage name="main">
      <work name="main" workers="2" totalOps="1">
        <operation type="write" ratio="100" config="containers=u(1,2);objects=u(1,2);content=zero;sizes=c(10)GB;chunked=true" />
      </work>
    </workstage>`

version  0.4.2.c4

what's  the problem?

my web server is Minio.   Minio 2.16.2017 release

when I use s3cmd upload the 10G file ,  the file chunked by s3cmd, and upload success.

**Comment by hrchu** [comment]
I think that large file cannot work in the chunk way.

**Comment by Saber-Yang** [comment]
Thank you for answer my issue

my web server is minio。
when I use s3cmd upload the 10G file , the file chunked by s3cmd, and upload success.

you mean, the cosbench cannot chunked the 10G file?how to use the chunked flag? 
when I write 5G and set chunked=true is also failed, the log messages is same.

Whether there are other configurations in order to make chunked flag effective for COSBench？

**Comment by Saber-Yang** [comment]
the chunk flag is uesless

**Comment by ghobson2013** [comment]
Cosbench should allow for the use of the TransferManager class for uploading large files.
its part of the com.amazonaws.services.s3.transfer package and would yield much higher throughput numbers.
Example if you set multipart size to 100MB, and upload a 1GB file, transfermanager would upload in parallel 10 x 100MB parts using s3 multipart instead of single PUT operations.

**Comment by Hacky-DH** [comment]
cosbench v0.4.2.c4
when I set chunked=true, in driver log error throws
java.lang.NegativeArraySizeException
	at com.intel.cosbench.api.librados.LibradosStorage.createObject(LibradosStorage.java:161)	
    at com.intel.cosbench.driver.operator.Writer.doWrite(Writer.java:98)
    at com.intel.cosbench.driver.operator.Preparer.operate(Preparer.java:97)
why in Preparer.java:94 set file length -1 when chunked is true?
long len = chunked ? -1 : size;

**Comment by qwer506** [comment]
Does anyone know how to solve this problem？
