### ISSUE TITLE
Driver hanging during boot

### ISSUE THREAD

**Issue by prtsh** [intel-cloud/cosbench#371]
I recently installed cosbench version 0.4.2.3 on debian jessie vm.
Cosbench hangs after runnning script start-all.sh, 

The screen-log is -

pratyush:~/cos$ sh start-all.sh
Launching osgi framwork ...
Successfully launched osgi framework!
Booting cosbench driver ...

<and now it hangs>

Is it a known issue? Any fix?

**Comment by prtsh** [comment]
the command "nc 0.0.0.0 18089" enters osgi> prompt and then is not returning back to the bash promt.

**Comment by fvennetier** [comment]
Hello. I got the same issue. You can edit https://github.com/intel-cloud/cosbench/blob/master/release/cosbench-start.sh#L83 and replace `echo "ss -s ACTIVE cosbench"` by `echo -e "ss -s ACTIVE cosbench\ndisconnect\n"`. This did the trick for me.

**Comment by prtsh** [comment]
Thank Florent,

I made it work by exiting after OSGI framework launch in cosbench-start.sh -

echo "Launching osgi framwork ... "

/usr/bin/nohup java -Dcosbench.tomcat.config=$TOMCAT_CONFIG -server -cp main/* org.eclipse.equinox.launcher.Main -configuration $OSGI_CONFIG -console $OSGI_CONSOLE_PORT 1> $BOOT_LOG 2>&1 &
.
.
.
exit <this line added>


It works, all the controller/driver services are running and can launch the workloads.
