### ISSUE TITLE
New version-0.4.7.7，based on intel-cosbench, openio-cosbench, thanks.

### ISSUE THREAD

**Issue by kisscelia** [intel-cloud/cosbench#422]
New version: 0.4.7.7:
https://github.com/kisscelia/cosbench
or
https://github.com/kisscelia/cosbench-ehualu

both OK.

Welcome, have a try. :)

**Comment by fvennetier** [comment]
Hello. When forking, you seem to have dropped the whole Git history. We cannot see what you have changed... :slightly_frowning_face:

**Comment by kisscelia** [comment]
> Hello. When forking, you seem to have dropped the whole Git history. We cannot see what you have changed... 🙁

Hi, @fvennetier 
you can see the README-ehualu.md

**Comment by kisscelia** [comment]
New version: 0.4.7.6:
https://github.com/kisscelia/cosbench
or
https://github.com/kisscelia/cosbench-ehualu

both OK.

Welcome, have a try. :)
